name: Flutter CI Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      
jobs:
  flutter-tests:
    runs-on: ubuntu-latest
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  flutter-ios:
      runs-on: macos-latest
      
      steps:
        - name: Clone repository
          uses: actions/checkout@v4
  
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: 3.24.4
  
        - name: Install CocoaPods
          run: |
            sudo gem install cocoapods
            cd ios && pod install
  
        - name: Install dependencies
          run: flutter pub get
  
        - name: Build iOS app
          run: flutter build ios --no-codesign
